{
  "formatVersion": "1.1",
  "component": {
    "url": "../../plain-common/0.1.2/plain-common-0.1.2.module",
    "group": "com.ismartcoding",
    "module": "plain-common",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.33.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "plain-common-iosArm64Main-0.1.2.klib",
          "url": "plain-common-iosarm64-0.1.2.klib",
          "size": 1174390,
          "sha512": "5bcfecb5981eae28a4dcc4c3c3b16bda068d0dc63978e7ef64ac661e4d0274d2c2354403919d847538ad47e88f66c24608033ceea1b69b507a77fad18b7fe8da",
          "sha256": "71f82e8f85094d8ba281a49130842983d9ce6c404ec143e1fb3f0830d72e3b41",
          "sha1": "2365502ae7bfb5976c5e855d65bf8e0b821fdca9",
          "md5": "d0316d7368acfe60b53b13f55b1b5001"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "plain-common-iosarm64-0.1.2-sources.jar",
          "url": "plain-common-iosarm64-0.1.2-sources.jar",
          "size": 267742,
          "sha512": "1b34dc4116920f7b10ccf9ce99718d5728a2c2c3651ff3a140d070dcd9c284ab723ac00d246ff9e190afd7c4c1bd5849f65d7861ae982394feef3ceb9a6f70c0",
          "sha256": "97670ad6619caae59234b39b349e53b869d519a02af817dcd657db248075b3c5",
          "sha1": "fb64d64f3d975bd684a6396a2554448ab1ce721b",
          "md5": "6987b6bf32bb69518ff4f4d530d174b6"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.33.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "plain-common-iosarm64-0.1.2-metadata.jar",
          "url": "plain-common-iosarm64-0.1.2-metadata.jar",
          "size": 6403,
          "sha512": "dc2b7e6bf0a83a877f3c8be56c0a9c550429f52c189e49c1bdfc41a220f342014f59979756364e87114fa7ace5c176ae3fbd001b615e29ff136e898d3cf4f270",
          "sha256": "86852ad2b0e532651960ca68006939060d050618483c2a188293a343bc275110",
          "sha1": "a1cab5f07e374f071281906cd7b91afcf22c8728",
          "md5": "16e9cd6eac246b48abf8b20c24d942ad"
        }
      ]
    }
  ]
}
