[package]
name = "plain-rust"
version = "0.1.0"
edition = "2024"

[lib]
name = "plain_rust"
crate-type = ["cdylib", "staticlib"]

[dependencies]
plain-rs = { git = "https://github.com/plainhub/plain-desktop.git", rev = "cd4a200d5cebf58cd0db6e0b0aefc63a144daf62", features = ["content_api", "http_transport"] }
serde_json = "1"
rustls-pemfile = "2"
tokio = { version = "1", features = ["rt-multi-thread", "sync"] }

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.22"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
strip = "symbols"
