{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ismartcoding",
    "module": "plain-common",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.32.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "plain-common-metadata-0.1.0.jar",
          "url": "plain-common-0.1.0.jar",
          "size": 192691,
          "sha512": "160945eb7f2716b3d32ec3134d0f64c90800e03ea6d8a14bd487ba23b25ee7ce58201a2e5c7c77920ca4a71e2bab93d29759dd47fe7efe9b0fcd12ad8c12c2a6",
          "sha256": "89dd24da045ed15154ebbd23b9d68922df6455aad1faaed62875b41c58c3a059",
          "sha1": "2eeeb65cb2ef1f980b4ac082dc778ba71c62ad4d",
          "md5": "6344d6be0307fcf76d0d6be0053322ca"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "plain-common-kotlin-0.1.0-sources.jar",
          "url": "plain-common-0.1.0-sources.jar",
          "size": 266887,
          "sha512": "a9cfb3b41934a711a3ac23820c2bec1a73a0b4278798dfad337606064c19ce38a276bd92019999dd21c495c7cfeffe2bce047dc1cea33b85de3810198d94a596",
          "sha256": "843aa539c79ca57764a05e2efd90b3539f7601583ef91e7ed0602ddf2ca8aed3",
          "sha1": "96e04361b16b5a0aa039f8a2893114a1020c9098",
          "md5": "08f336d82f2875fe6b941518739bce5a"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../plain-common-android/0.1.0/plain-common-android-0.1.0.module",
        "group": "com.ismartcoding",
        "module": "plain-common-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../plain-common-android/0.1.0/plain-common-android-0.1.0.module",
        "group": "com.ismartcoding",
        "module": "plain-common-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../plain-common-android/0.1.0/plain-common-android-0.1.0.module",
        "group": "com.ismartcoding",
        "module": "plain-common-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-common-iosarm64/0.1.0/plain-common-iosarm64-0.1.0.module",
        "group": "com.ismartcoding",
        "module": "plain-common-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-common-iosarm64/0.1.0/plain-common-iosarm64-0.1.0.module",
        "group": "com.ismartcoding",
        "module": "plain-common-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-common-iosarm64/0.1.0/plain-common-iosarm64-0.1.0.module",
        "group": "com.ismartcoding",
        "module": "plain-common-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-common-iossimulatorarm64/0.1.0/plain-common-iossimulatorarm64-0.1.0.module",
        "group": "com.ismartcoding",
        "module": "plain-common-iossimulatorarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-common-iossimulatorarm64/0.1.0/plain-common-iossimulatorarm64-0.1.0.module",
        "group": "com.ismartcoding",
        "module": "plain-common-iossimulatorarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-common-iossimulatorarm64/0.1.0/plain-common-iossimulatorarm64-0.1.0.module",
        "group": "com.ismartcoding",
        "module": "plain-common-iossimulatorarm64",
        "version": "0.1.0"
      }
    }
  ]
}
