{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ismartcoding",
    "module": "plain-common",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.32.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "plain-common-metadata-0.1.0.jar",
          "url": "plain-common-0.1.0.jar",
          "size": 203554,
          "sha512": "b6d1c439867744d13d9228ad62dbdbe84108673e6f9b6f0aef65f7cac1edfb498f1a5f2dc72b27a6977df5cf2331c7bbe81d7760ac3df5806ba4b999a162a451",
          "sha256": "c3d067e5c43df5abee3de7edfe00da005842b61caca6aeaf5cb668f0839ef29e",
          "sha1": "95c36f70b77b1e17597a5885acc26db100f0c948",
          "md5": "a87f5f8c0a5f7975d4f30a09b2297c22"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "plain-common-kotlin-0.1.0-sources.jar",
          "url": "plain-common-0.1.0-sources.jar",
          "size": 278804,
          "sha512": "cc2fed636cc2e7f09103098bb476b167a06b70846dfd6826c0fc99e8aa8c425de4bb7d614ecb8ad5f1757fc0579ab877cf6c6a734057f25920bf5380cc93b2e1",
          "sha256": "12bbcace798f3de8b29d03cecd2223d693860186f049d5e0f395342604607f64",
          "sha1": "ab79bb85396152966aea04cdf9fffb440eed02de",
          "md5": "de1a16d6c9c1ff1cd15f28104e0d2fa6"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../plain-common-android/0.1.0/plain-common-android-0.1.0.module",
        "group": "com.ismartcoding",
        "module": "plain-common-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../plain-common-android/0.1.0/plain-common-android-0.1.0.module",
        "group": "com.ismartcoding",
        "module": "plain-common-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../plain-common-android/0.1.0/plain-common-android-0.1.0.module",
        "group": "com.ismartcoding",
        "module": "plain-common-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-common-iosarm64/0.1.0/plain-common-iosarm64-0.1.0.module",
        "group": "com.ismartcoding",
        "module": "plain-common-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-common-iosarm64/0.1.0/plain-common-iosarm64-0.1.0.module",
        "group": "com.ismartcoding",
        "module": "plain-common-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-common-iosarm64/0.1.0/plain-common-iosarm64-0.1.0.module",
        "group": "com.ismartcoding",
        "module": "plain-common-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-common-iossimulatorarm64/0.1.0/plain-common-iossimulatorarm64-0.1.0.module",
        "group": "com.ismartcoding",
        "module": "plain-common-iossimulatorarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-common-iossimulatorarm64/0.1.0/plain-common-iossimulatorarm64-0.1.0.module",
        "group": "com.ismartcoding",
        "module": "plain-common-iossimulatorarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-common-iossimulatorarm64/0.1.0/plain-common-iossimulatorarm64-0.1.0.module",
        "group": "com.ismartcoding",
        "module": "plain-common-iossimulatorarm64",
        "version": "0.1.0"
      }
    }
  ]
}
