package com.ismartcoding.plain.preferences

import com.ismartcoding.plain.data.*
import kotlinx.serialization.Serializable

@Serializable
data class UserSettings(
    val httpPort: Int,
    val httpsPort: Int,
    val darkTheme: Int,
    val amoledDarkTheme: Boolean,
    val pdfFollowDarkTheme: Boolean,
    val keepAwake: Boolean,
    val locale: String,
    val service: Boolean,
    val desktopAccess: Boolean,
    val dlna: Boolean,
    val developerMode: Boolean,
    val allowAnyHost: Boolean,
    val deviceName: String,
    val https: Boolean,
    val webAddressBarExpanded: Boolean,
    val screenMirrorQuality: DScreenMirrorQuality,
    val audioPlayMode: Int,
    val audioPlaybackSpeed: Float,
    val imageGridCellsPerRow: Int,
    val videoGridCellsPerRow: Int,
    val showHiddenFiles: Boolean,
    val feedAutoRefresh: Boolean,
    val feedAutoRefreshIntervalSec: Int,
    val feedAutoRefreshOnlyWifi: Boolean,
    val feedFontScale: Int,
    val editorWrapContent: Boolean,
    val editorFontSize: Int,
    val editorStatusBar: Boolean,
    val lastFilePath: FilePathData,
    val scanHistory: List<String>,
    val audioPlaylist: List<com.ismartcoding.plain.audio.DPlaylistAudio>,
    val chatInputText: String,
    val nearbyDiscoverable: Boolean,
    val aiImageSearchEnabled: Boolean,
    val notificationFilter: NotificationFilterData,
    val pomodoroSettings: DPomodoroSettings,
    val videoPlaylist: List<DVideo>,
    val homeFeatures: String,
    val quickNoteDraft: String,
    val launcherShortcuts: String,
    val recentSearches: List<String>,
    val recentSaveDirs: List<String>,
    val audioSortBy: Int,
    val videoSortBy: Int,
    val imageSortBy: Int,
    val docSortBy: Int,
    val fileSortBy: Int,
    val packageSortBy: Int,
)
