package com.ismartcoding.plain.preferences

import com.ismartcoding.plain.data.*
import kotlinx.serialization.Serializable

@Serializable
data class UserSettingsPatch(
    val httpPort: Int? = null,
    val httpsPort: Int? = null,
    val darkTheme: Int? = null,
    val amoledDarkTheme: Boolean? = null,
    val pdfFollowDarkTheme: Boolean? = null,
    val keepAwake: Boolean? = null,
    val locale: String? = null,
    val service: Boolean? = null,
    val desktopAccess: Boolean? = null,
    val dlna: Boolean? = null,
    val developerMode: Boolean? = null,
    val allowAnyHost: Boolean? = null,
    val deviceName: String? = null,
    val https: Boolean? = null,
    val webAddressBarExpanded: Boolean? = null,
    val screenMirrorQuality: DScreenMirrorQuality? = null,
    val audioPlayMode: Int? = null,
    val audioPlaybackSpeed: Float? = null,
    val imageGridCellsPerRow: Int? = null,
    val videoGridCellsPerRow: Int? = null,
    val showHiddenFiles: Boolean? = null,
    val feedAutoRefresh: Boolean? = null,
    val feedAutoRefreshIntervalSec: Int? = null,
    val feedAutoRefreshOnlyWifi: Boolean? = null,
    val feedFontScale: Int? = null,
    val editorWrapContent: Boolean? = null,
    val editorFontSize: Int? = null,
    val editorStatusBar: Boolean? = null,
    val lastFilePath: FilePathData? = null,
    val scanHistory: List<String>? = null,
    val audioPlaylist: List<com.ismartcoding.plain.audio.DPlaylistAudio>? = null,
    val chatInputText: String? = null,
    val nearbyDiscoverable: Boolean? = null,
    val aiImageSearchEnabled: Boolean? = null,
    val notificationFilter: NotificationFilterData? = null,
    val pomodoroSettings: DPomodoroSettings? = null,
    val videoPlaylist: List<DVideo>? = null,
    val homeFeatures: String? = null,
    val quickNoteDraft: String? = null,
    val launcherShortcuts: String? = null,
    val recentSearches: List<String>? = null,
    val recentSaveDirs: List<String>? = null,
    val audioSortBy: Int? = null,
    val videoSortBy: Int? = null,
    val imageSortBy: Int? = null,
    val docSortBy: Int? = null,
    val fileSortBy: Int? = null,
    val packageSortBy: Int? = null,
)
