{
  "formatVersion": "1.1",
  "component": {
    "url": "../../plain-ui/0.3.1/plain-ui-0.3.1.module",
    "group": "com.ismartcoding",
    "module": "plain-ui",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.4"
          }
        },
        {
          "group": "com.ismartcoding",
          "module": "plain-common",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.33.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "plain-ui.aar",
          "url": "plain-ui-android-0.3.1.aar",
          "size": 972211,
          "sha512": "06a75b02c35b3d1a241d5a9f9b9584c825aef1ad6df348328b284b0df97878ff37b7c4262648bffb49a0cb562aef6375664c341b8310a56cd661b55830106197",
          "sha256": "acb1ee386b89d927be442cc0795a98be0226fbb3d2bcb66e96d3ea98b9d41e97",
          "sha1": "7c3dca579582abf2e0c39b22de52f24cfc5bbf1e",
          "md5": "52cfbbc8148c4879497c14831c56e23d"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.4"
          }
        },
        {
          "group": "com.ismartcoding",
          "module": "plain-common",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.33.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "plain-ui.aar",
          "url": "plain-ui-android-0.3.1.aar",
          "size": 972211,
          "sha512": "06a75b02c35b3d1a241d5a9f9b9584c825aef1ad6df348328b284b0df97878ff37b7c4262648bffb49a0cb562aef6375664c341b8310a56cd661b55830106197",
          "sha256": "acb1ee386b89d927be442cc0795a98be0226fbb3d2bcb66e96d3ea98b9d41e97",
          "sha1": "7c3dca579582abf2e0c39b22de52f24cfc5bbf1e",
          "md5": "52cfbbc8148c4879497c14831c56e23d"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "plain-ui-android-0.3.1-sources.jar",
          "url": "plain-ui-android-0.3.1-sources.jar",
          "size": 142563,
          "sha512": "2d8f46c28881cfecb6a7aca5782b6d06daff49ac36081cfb2e008e57c63a848c1385f55addb4bf9fb9da3c556171790afbcca0199a328aa79a41531390028b06",
          "sha256": "c7a570b1bc7af1a2fb43feb5680aa56f7665e2b9adc38a44cd5cd527207f048d",
          "sha1": "41adf886059f836bf70ec091e380dd4d769d0853",
          "md5": "a6bf95c6126d0aa2d75df292cb5e10ed"
        }
      ]
    }
  ]
}
