files:
  - source: /app/src/main/res/values/strings.xml
    ignore:
      - /app/src/main/res/values-night/**
    translation: /app/src/main/res/values-%two_letters_code%/strings.xml
    type: android
  - source: /app/src/main/res/values/plurals.xml
    ignore:
      - /app/src/main/res/values-night/**
    translation: /app/src/main/res/values-%two_letters_code%/plurals.xml
    type: android
