files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%two_letters_code%/strings.xml
    type: android

  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-zh-rCN/strings.xml
    languages_mapping:
      two_letters_code:
        zh-CN: zh-rCN

  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-zh-rTW/strings.xml
    languages_mapping:
      two_letters_code:
        zh-TW: zh-rTW