{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ismartcoding",
    "module": "plain-ui",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.ismartcoding",
          "module": "plain-common",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.33.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "plain-ui-metadata-0.4.0.jar",
          "url": "plain-ui-0.4.0.jar",
          "size": 98864,
          "sha512": "4220460f4d2cd04a7c933eea90b16d58de98caeeb5bcc87da55dd528c295de85a10ad1b4f18db192fe0c519f01e2e6945d64202da2663f393abaed1321cdc27c",
          "sha256": "b35ffd911411c27ca3c8e06b67fa6c31598a6539a1316200dba52342aa508c62",
          "sha1": "95c29a2384143f23f7eef8e24a6c2047ab49d3d3",
          "md5": "1b255e578b84d837a23237be6f01f11e"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "plain-ui-kotlin-0.4.0-sources.jar",
          "url": "plain-ui-0.4.0-sources.jar",
          "size": 151420,
          "sha512": "b66f7d122d0e6006a5a998b0a72df4d76daf590b98ffb68a120129fce5db23da29f25d056d5b15d2eb12bcd794914a9b7276803e2df3434fff30a0735d1856ff",
          "sha256": "9b95f3775e459a136efe76fdcc49c52b5a86b3558caa3a05e31b455efd8e55f0",
          "sha1": "58271eedc49d848b1be3ce94b3f0e0b04e1d88f3",
          "md5": "cca5fdd9bf945860b9dd9862132ba759"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../plain-ui-android/0.4.0/plain-ui-android-0.4.0.module",
        "group": "com.ismartcoding",
        "module": "plain-ui-android",
        "version": "0.4.0"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../plain-ui-android/0.4.0/plain-ui-android-0.4.0.module",
        "group": "com.ismartcoding",
        "module": "plain-ui-android",
        "version": "0.4.0"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../plain-ui-android/0.4.0/plain-ui-android-0.4.0.module",
        "group": "com.ismartcoding",
        "module": "plain-ui-android",
        "version": "0.4.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-ui-iosarm64/0.4.0/plain-ui-iosarm64-0.4.0.module",
        "group": "com.ismartcoding",
        "module": "plain-ui-iosarm64",
        "version": "0.4.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-ui-iosarm64/0.4.0/plain-ui-iosarm64-0.4.0.module",
        "group": "com.ismartcoding",
        "module": "plain-ui-iosarm64",
        "version": "0.4.0"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-ui-iosarm64/0.4.0/plain-ui-iosarm64-0.4.0.module",
        "group": "com.ismartcoding",
        "module": "plain-ui-iosarm64",
        "version": "0.4.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-ui-iosarm64/0.4.0/plain-ui-iosarm64-0.4.0.module",
        "group": "com.ismartcoding",
        "module": "plain-ui-iosarm64",
        "version": "0.4.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-ui-iossimulatorarm64/0.4.0/plain-ui-iossimulatorarm64-0.4.0.module",
        "group": "com.ismartcoding",
        "module": "plain-ui-iossimulatorarm64",
        "version": "0.4.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-ui-iossimulatorarm64/0.4.0/plain-ui-iossimulatorarm64-0.4.0.module",
        "group": "com.ismartcoding",
        "module": "plain-ui-iossimulatorarm64",
        "version": "0.4.0"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-ui-iossimulatorarm64/0.4.0/plain-ui-iossimulatorarm64-0.4.0.module",
        "group": "com.ismartcoding",
        "module": "plain-ui-iossimulatorarm64",
        "version": "0.4.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-ui-iossimulatorarm64/0.4.0/plain-ui-iossimulatorarm64-0.4.0.module",
        "group": "com.ismartcoding",
        "module": "plain-ui-iossimulatorarm64",
        "version": "0.4.0"
      }
    }
  ]
}
