{
  "formatVersion": "1.1",
  "component": {
    "url": "../../plain-ui/0.1.0/plain-ui-0.1.0.module",
    "group": "com.ismartcoding",
    "module": "plain-ui",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "plain-ui-iosSimulatorArm64Main-0.1.0.klib",
          "url": "plain-ui-iossimulatorarm64-0.1.0.klib",
          "size": 19428,
          "sha512": "f2ed0c508062e15e9c976b2248314f8fe277bafb6720f10aedc450dd36f7da5b9fc435b3d79427bec822548f582a1b28b8a9987f27fe5ba0e76afd7724fa0c65",
          "sha256": "ad34e8dc4026c46c3324757617e80bbbee407251bed09c4d38e725ad2f6733bf",
          "sha1": "c3b279d485e6e9d426fe5c7f2f508c2b3113d25d",
          "md5": "e7a1a05a0f19a707d72ada98a7c5ea89"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "plain-ui-iossimulatorarm64-0.1.0-sources.jar",
          "url": "plain-ui-iossimulatorarm64-0.1.0-sources.jar",
          "size": 2797,
          "sha512": "a855ea8aa98ff2deb91983bbef5147eb312fe58a9e4a3027d5224177419980150740b1859631c96a27d8cd398a818b2ba76a29b859b5edef76d14f8b77294582",
          "sha256": "be14aabd073803fe30148c10694c4b43d063f79744e62c1debf038845f5119ed",
          "sha1": "abd951c2789e2a3d95d19ac585e61f93e0d8326d",
          "md5": "a9924d7ba1f3221d8391bdfc11ca08c1"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "plain-ui-0.1.0.kotlin_resources.zip",
          "url": "plain-ui-iossimulatorarm64-0.1.0-kotlin_resources.kotlin_resources.zip",
          "size": 338,
          "sha512": "8c44d4b74a687e6b40b01ef6d6177b3a6d91b9cc16836b30ea491798cba25ba68ab4f059dddf977f64abc72b412c25ba8b2c16cd83d68582cfe8edd34715daf4",
          "sha256": "eef22e641385544f8a5d970ce3707c5412ac17bb324513c0f63368ac98a71d22",
          "sha1": "4c629801be5df763a7ebce974bdceb2e4169590e",
          "md5": "6f68f843241210adaf61b25e782dd889"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "plain-ui-iossimulatorarm64-0.1.0-metadata.jar",
          "url": "plain-ui-iossimulatorarm64-0.1.0-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
