{
  "formatVersion": "1.1",
  "component": {
    "url": "../../plain-common/0.1.7/plain-common-0.1.7.module",
    "group": "com.ismartcoding",
    "module": "plain-common",
    "version": "0.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.19.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.33.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "plain-common.aar",
          "url": "plain-common-android-0.1.7.aar",
          "size": 415345,
          "sha512": "9eacd73481c0ab7e6fbd98ebfe926988af3d8ec60ce9096965169c5cece4f01049b6e87f62c9482227c0275398016c430494b47add3508b9e4afee3da5e0d1d9",
          "sha256": "809dbf5f6d6fc756f2347cb17a748ce8d0a3da31928cea2d05273aab8b600b47",
          "sha1": "5c4d0c12641dde3d143ad8ce378853192d54d17e",
          "md5": "4933ac0932781e7882219e615340dbfa"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.19.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.33.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "plain-common.aar",
          "url": "plain-common-android-0.1.7.aar",
          "size": 415345,
          "sha512": "9eacd73481c0ab7e6fbd98ebfe926988af3d8ec60ce9096965169c5cece4f01049b6e87f62c9482227c0275398016c430494b47add3508b9e4afee3da5e0d1d9",
          "sha256": "809dbf5f6d6fc756f2347cb17a748ce8d0a3da31928cea2d05273aab8b600b47",
          "sha1": "5c4d0c12641dde3d143ad8ce378853192d54d17e",
          "md5": "4933ac0932781e7882219e615340dbfa"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "plain-common-android-0.1.7-sources.jar",
          "url": "plain-common-android-0.1.7-sources.jar",
          "size": 111261,
          "sha512": "e6fec4e99f1ed849d039e17acecc52f39d0c45567e3ec924a76c6f3c43e163ba16cc37bed1261fa7cb78212698eafc7cd424db47d9d2566c213193c75354dc6c",
          "sha256": "27fc2b9de6cb061e1c64d7caf8482881e467138c1e5a7aa0d856c8e1aef06a15",
          "sha1": "f9fa37d3cdbf520d4fb99d8884f68d2d0b68a5d8",
          "md5": "604581de228f56a1337f0ce4327321be"
        }
      ]
    }
  ]
}
