{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ismartcoding",
    "module": "plain-common",
    "version": "0.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.33.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "plain-common-metadata-0.1.6.jar",
          "url": "plain-common-0.1.6.jar",
          "size": 69422,
          "sha512": "b6758030a0d16c82e2d25dc19b91e26f6dcf14e23b2267ca30789cea6174e20cff96832467d6ad14e6217253e85ab759926ee7130136c0f35687f5f500d98cb1",
          "sha256": "cbfd52337df539129f008bafb17169458ebad39a43d6f50989da8aa2db49d130",
          "sha1": "1d83718d372a32fc69f1504c87a901d0d1fd996a",
          "md5": "4fece475e86378b90862b5f887319f81"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "plain-common-kotlin-0.1.6-sources.jar",
          "url": "plain-common-0.1.6-sources.jar",
          "size": 141132,
          "sha512": "266b85169ed89ac87d2e98f7ebce913b40d58ecdc75b09e1a52d5eb3b71f6d606762cfb4fb34f2e68d1b521be29b46dc12749dc3f3c0a460609d27218b2e8422",
          "sha256": "8065b7f5f8ddf3bbb7fc85dd4470290715ed8628e0bc9385082802aaf7409e17",
          "sha1": "32fec0a93de5688615d8d61e99e756e123e2329b",
          "md5": "9e8c8be26287809adadb9433fb83ca81"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../plain-common-android/0.1.6/plain-common-android-0.1.6.module",
        "group": "com.ismartcoding",
        "module": "plain-common-android",
        "version": "0.1.6"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../plain-common-android/0.1.6/plain-common-android-0.1.6.module",
        "group": "com.ismartcoding",
        "module": "plain-common-android",
        "version": "0.1.6"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../plain-common-android/0.1.6/plain-common-android-0.1.6.module",
        "group": "com.ismartcoding",
        "module": "plain-common-android",
        "version": "0.1.6"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-common-iosarm64/0.1.6/plain-common-iosarm64-0.1.6.module",
        "group": "com.ismartcoding",
        "module": "plain-common-iosarm64",
        "version": "0.1.6"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-common-iosarm64/0.1.6/plain-common-iosarm64-0.1.6.module",
        "group": "com.ismartcoding",
        "module": "plain-common-iosarm64",
        "version": "0.1.6"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-common-iosarm64/0.1.6/plain-common-iosarm64-0.1.6.module",
        "group": "com.ismartcoding",
        "module": "plain-common-iosarm64",
        "version": "0.1.6"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-common-iossimulatorarm64/0.1.6/plain-common-iossimulatorarm64-0.1.6.module",
        "group": "com.ismartcoding",
        "module": "plain-common-iossimulatorarm64",
        "version": "0.1.6"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-common-iossimulatorarm64/0.1.6/plain-common-iossimulatorarm64-0.1.6.module",
        "group": "com.ismartcoding",
        "module": "plain-common-iossimulatorarm64",
        "version": "0.1.6"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-common-iossimulatorarm64/0.1.6/plain-common-iossimulatorarm64-0.1.6.module",
        "group": "com.ismartcoding",
        "module": "plain-common-iossimulatorarm64",
        "version": "0.1.6"
      }
    }
  ]
}
