{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ismartcoding",
    "module": "plain-common",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.33.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "plain-common-metadata-0.1.2.jar",
          "url": "plain-common-0.1.2.jar",
          "size": 193443,
          "sha512": "04e11b5638f09c930bcbfa93453982dd5b7297d09aa022c439c0165ec642cacc5eea040e5d2366c0a931c8213b08dc7c25ec6d3f7ac0e8ce4c98752bcfb28b0e",
          "sha256": "9a71e10cf10959bdae8a2edbbf926bed49c60cb21329ee0b47644995fb37852f",
          "sha1": "59aa6710bc6b3d09578520cddc989f05b752fc94",
          "md5": "1a7e57fedfb7001756788108b9583d0f"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "plain-common-kotlin-0.1.2-sources.jar",
          "url": "plain-common-0.1.2-sources.jar",
          "size": 267742,
          "sha512": "a9dbeb9955f37f6d82ead9f92c0f1bce5ef33b95226684db4ae602999d9c5adb9fc3700e96fa7b8dd194213564be06906bbdfe869ac8527335397b1ad8cf0650",
          "sha256": "76b517e4b3bc8721279dbd8b4331113855468739b43df5e16624b6db54d3fa89",
          "sha1": "3b9007cc13126ee15e4c7c84f79a288670cd1bbb",
          "md5": "1e6e5c76c67d131c2e0e44f069c5dcdc"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../plain-common-android/0.1.2/plain-common-android-0.1.2.module",
        "group": "com.ismartcoding",
        "module": "plain-common-android",
        "version": "0.1.2"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../plain-common-android/0.1.2/plain-common-android-0.1.2.module",
        "group": "com.ismartcoding",
        "module": "plain-common-android",
        "version": "0.1.2"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../plain-common-android/0.1.2/plain-common-android-0.1.2.module",
        "group": "com.ismartcoding",
        "module": "plain-common-android",
        "version": "0.1.2"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-common-iosarm64/0.1.2/plain-common-iosarm64-0.1.2.module",
        "group": "com.ismartcoding",
        "module": "plain-common-iosarm64",
        "version": "0.1.2"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-common-iosarm64/0.1.2/plain-common-iosarm64-0.1.2.module",
        "group": "com.ismartcoding",
        "module": "plain-common-iosarm64",
        "version": "0.1.2"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-common-iosarm64/0.1.2/plain-common-iosarm64-0.1.2.module",
        "group": "com.ismartcoding",
        "module": "plain-common-iosarm64",
        "version": "0.1.2"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-common-iossimulatorarm64/0.1.2/plain-common-iossimulatorarm64-0.1.2.module",
        "group": "com.ismartcoding",
        "module": "plain-common-iossimulatorarm64",
        "version": "0.1.2"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-common-iossimulatorarm64/0.1.2/plain-common-iossimulatorarm64-0.1.2.module",
        "group": "com.ismartcoding",
        "module": "plain-common-iossimulatorarm64",
        "version": "0.1.2"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-common-iossimulatorarm64/0.1.2/plain-common-iossimulatorarm64-0.1.2.module",
        "group": "com.ismartcoding",
        "module": "plain-common-iossimulatorarm64",
        "version": "0.1.2"
      }
    }
  ]
}
