{
  "formatVersion": "1.1",
  "component": {
    "url": "../../plain-common/0.1.0/plain-common-0.1.0.module",
    "group": "com.ismartcoding",
    "module": "plain-common",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.32.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "plain-common-iosArm64Main-0.1.0.klib",
          "url": "plain-common-iosarm64-0.1.0.klib",
          "size": 1171761,
          "sha512": "0a4f45cb707e2a022b0ea4935146efa08f74a106486edc2aadf61763b8f4e434c947a801591fe32ba9588181b3d7e91a1b088ea013691a12d78a5feee3b0ece5",
          "sha256": "293cbcecad3e37ca044570b44169b7ba5df7d0fd9a371558de15fece5a7cbcc2",
          "sha1": "666ddb442881e304d88c57d37b18b1d57dc38543",
          "md5": "63129124ffb32e95cc2d984b6741af6c"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "plain-common-iosarm64-0.1.0-sources.jar",
          "url": "plain-common-iosarm64-0.1.0-sources.jar",
          "size": 266887,
          "sha512": "fabfddc87561000adb2edfb77d5a9eb96c56ddc51e996db0f7953395e03b081dfc62df0e93a82788f512cc5bcc59f5680a7bd48e0a29084c243115d83aba9683",
          "sha256": "0f83a6c93b496609fedfcd7e4f35cb7b98e3cd07720e445c576669c9b28d0157",
          "sha1": "57f60fb94a5582ad64ed73dc55f5e3cd4d4098dc",
          "md5": "4f077311fd99d1f4bea40a7230e305a6"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.32.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "plain-common-iosarm64-0.1.0-metadata.jar",
          "url": "plain-common-iosarm64-0.1.0-metadata.jar",
          "size": 6403,
          "sha512": "b0feafeadbc28b65d1e677f9138fbe4c264e1605d51e1ebe3c434400b198824f5608a3455c1c92401f2c28d5eedc939bbf75c9e7a1383f93c5446b17ba0a58e6",
          "sha256": "725781ac7ba208b9bbdfe53d20130011887f4d2a3d6c191d80d4bf666e31cad6",
          "sha1": "a6a9395631ccac72e637a2095c63606afdbc8c40",
          "md5": "7b559d828339ea9590f8e723e114d572"
        }
      ]
    }
  ]
}
