{
  "formatVersion": "1.1",
  "component": {
    "url": "../../plain-ui/0.4.6/plain-ui-0.4.6.module",
    "group": "com.ismartcoding",
    "module": "plain-ui",
    "version": "0.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.4"
          }
        },
        {
          "group": "com.ismartcoding",
          "module": "plain-common",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.33.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "plain-ui.aar",
          "url": "plain-ui-android-0.4.6.aar",
          "size": 1165303,
          "sha512": "1d876a6c6edac52a4b9c66dc00a961ac4b494d1e115aedb970d4835f0acdb5c2062777592dd25d481227b9d118291b64ea16dbaa3921f8982c82c26584ab3092",
          "sha256": "1604d69b6f319d49531681351d18cb3759fb2e6f6bf7728eb9cdfc9a43334a55",
          "sha1": "f09bc360dc080664e270a00756390e63c8e92611",
          "md5": "f0edf2ad9151f9e00b8c6add50ed93c9"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.4"
          }
        },
        {
          "group": "com.ismartcoding",
          "module": "plain-common",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.33.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-compose",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "plain-ui.aar",
          "url": "plain-ui-android-0.4.6.aar",
          "size": 1165303,
          "sha512": "1d876a6c6edac52a4b9c66dc00a961ac4b494d1e115aedb970d4835f0acdb5c2062777592dd25d481227b9d118291b64ea16dbaa3921f8982c82c26584ab3092",
          "sha256": "1604d69b6f319d49531681351d18cb3759fb2e6f6bf7728eb9cdfc9a43334a55",
          "sha1": "f09bc360dc080664e270a00756390e63c8e92611",
          "md5": "f0edf2ad9151f9e00b8c6add50ed93c9"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "plain-ui-android-0.4.6-sources.jar",
          "url": "plain-ui-android-0.4.6-sources.jar",
          "size": 176541,
          "sha512": "3ada28f25b0f164b418b6ef03e48c7d9b51300b71009194ca173d33b7a4737c5687041a9e37e40db0cc21d03cf92c57dd41885b69b6a758e7cde722bd0d9a692",
          "sha256": "a606496f4b638ffe489fdf58550c2e31f6633cc2bde98fd968d72aee9bf6c700",
          "sha1": "b15944ea0660ea4efe327907575b42d672ff9b84",
          "md5": "0d5cfb7372bc65ed37a72b8b7831f36a"
        }
      ]
    }
  ]
}
