{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ismartcoding",
    "module": "plain-ui",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.ismartcoding",
          "module": "plain-common",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.33.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "plain-ui-metadata-0.3.0.jar",
          "url": "plain-ui-0.3.0.jar",
          "size": 91513,
          "sha512": "33f07e4ec918710bc22589a85f33b2621f262d8b55fe7b715c706678f5a9e7bd889a722771b56bd54839ea379a024f417200c07d5d25a9236718cab9548ed5f9",
          "sha256": "a7f971bd9c9177c551f69f8292e7c7fd900fdec3e01c2f59ce8b3baeec7ec964",
          "sha1": "7204dd3be148edc02da463e1f1e8ddd02a93a1f9",
          "md5": "9b5f44895596c3bb80d86b6ba7924c3d"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "plain-ui-kotlin-0.3.0-sources.jar",
          "url": "plain-ui-0.3.0-sources.jar",
          "size": 137074,
          "sha512": "188d73e076f59150c9e6f4c321a91dea41bb848a97c3debcd36f913c601d594c2bcd061b39fa1feb686b2a45b1c0566ec5ead58c05d4a2350e487cd07dde5d5e",
          "sha256": "ec89d2ac13e1c4bb0fdda652796227dc991c32bd071e5c452896838a97a69a45",
          "sha1": "a0cddc417fef2681e518c9adae8b1c7afd431636",
          "md5": "61162db64c922380f3f8d1360a03bf40"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../plain-ui-android/0.3.0/plain-ui-android-0.3.0.module",
        "group": "com.ismartcoding",
        "module": "plain-ui-android",
        "version": "0.3.0"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../plain-ui-android/0.3.0/plain-ui-android-0.3.0.module",
        "group": "com.ismartcoding",
        "module": "plain-ui-android",
        "version": "0.3.0"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../plain-ui-android/0.3.0/plain-ui-android-0.3.0.module",
        "group": "com.ismartcoding",
        "module": "plain-ui-android",
        "version": "0.3.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-ui-iosarm64/0.3.0/plain-ui-iosarm64-0.3.0.module",
        "group": "com.ismartcoding",
        "module": "plain-ui-iosarm64",
        "version": "0.3.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-ui-iosarm64/0.3.0/plain-ui-iosarm64-0.3.0.module",
        "group": "com.ismartcoding",
        "module": "plain-ui-iosarm64",
        "version": "0.3.0"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-ui-iosarm64/0.3.0/plain-ui-iosarm64-0.3.0.module",
        "group": "com.ismartcoding",
        "module": "plain-ui-iosarm64",
        "version": "0.3.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-ui-iosarm64/0.3.0/plain-ui-iosarm64-0.3.0.module",
        "group": "com.ismartcoding",
        "module": "plain-ui-iosarm64",
        "version": "0.3.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-ui-iossimulatorarm64/0.3.0/plain-ui-iossimulatorarm64-0.3.0.module",
        "group": "com.ismartcoding",
        "module": "plain-ui-iossimulatorarm64",
        "version": "0.3.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-ui-iossimulatorarm64/0.3.0/plain-ui-iossimulatorarm64-0.3.0.module",
        "group": "com.ismartcoding",
        "module": "plain-ui-iossimulatorarm64",
        "version": "0.3.0"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-ui-iossimulatorarm64/0.3.0/plain-ui-iossimulatorarm64-0.3.0.module",
        "group": "com.ismartcoding",
        "module": "plain-ui-iossimulatorarm64",
        "version": "0.3.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-ui-iossimulatorarm64/0.3.0/plain-ui-iossimulatorarm64-0.3.0.module",
        "group": "com.ismartcoding",
        "module": "plain-ui-iossimulatorarm64",
        "version": "0.3.0"
      }
    }
  ]
}
