{
  "formatVersion": "1.1",
  "component": {
    "url": "../../plain-ui/0.3.0/plain-ui-0.3.0.module",
    "group": "com.ismartcoding",
    "module": "plain-ui",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.ismartcoding",
          "module": "plain-common",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.33.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "plain-ui-iosSimulatorArm64Main-0.3.0.klib",
          "url": "plain-ui-iossimulatorarm64-0.3.0.klib",
          "size": 758991,
          "sha512": "763355d3b08006de444c2528f4c0fc5da6943a267b450868ea743d4a9275dd433eedca1e371a4378672ace94a2144e86ac480e6924249f6210ab4e5267315736",
          "sha256": "05b659a83c13c78ef160f5d91255c94d118f3aef4f575e288b642b9ea3d402bd",
          "sha1": "8df9fa6e0510c3844f518ce5efed4d3c7e4f5d0d",
          "md5": "3d1f8e2d22bff425d23325a146d88fce"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "plain-ui-iossimulatorarm64-0.3.0-sources.jar",
          "url": "plain-ui-iossimulatorarm64-0.3.0-sources.jar",
          "size": 138593,
          "sha512": "82c6c0fd9a57e0ffe56d0e50477a00ada43953c1832d633b0c17fe3744f060f6c2e6f675e04624d3867cb40fb7ee7da0e98b69d6dff4f8ae1c9900f4512abf9f",
          "sha256": "2a80b1568b355bf3a00a78f3bdb5cf504c5fb5c83525fe590a96a450f7108d69",
          "sha1": "17b57be0f00d3b57f9abbd727d64425671d47278",
          "md5": "ad320c11dd4b39f55630a92e3627c6f7"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.ismartcoding",
          "module": "plain-common",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.33.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "plain-ui-0.3.0.kotlin_resources.zip",
          "url": "plain-ui-iossimulatorarm64-0.3.0-kotlin_resources.kotlin_resources.zip",
          "size": 114762,
          "sha512": "4ebba61158cbe561927d467e79828a2027aecf7c730b57b218932747541e614e3ec8edb4a96c95c11c335e8c29527e5a107d54c34a21f29bb0425aa090db2411",
          "sha256": "e25bf66fdd6ab565a9f4ad7cba313a3a530dd3a70b3d319824ec146977f0be42",
          "sha1": "4c0f46adb0975a7728cc8d884d016b8b61487fac",
          "md5": "2fdadf0c46e2af9d314ad929336c3990"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.ismartcoding",
          "module": "plain-common",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.33.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "plain-ui-iossimulatorarm64-0.3.0-metadata.jar",
          "url": "plain-ui-iossimulatorarm64-0.3.0-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
