{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ismartcoding",
    "module": "plain-ui",
    "version": "0.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.ismartcoding",
          "module": "plain-common",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.33.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "plain-ui-metadata-0.4.3.jar",
          "url": "plain-ui-0.4.3.jar",
          "size": 97908,
          "sha512": "a008a43ea5bae624ffc8e44d8d5035b4bb20a4fcc1b480aa913f85d3af08d60bfc526990d9e518dc895002fe03adcc4d451275d84f676c0b8bba6cb0d321a66a",
          "sha256": "a9416b3aeb0c53d1322a92d7543d6cd5fefa3f3fb80fabca04470acc63e1c00b",
          "sha1": "01bd52170486b3d29154b7904269f48cfb3f7215",
          "md5": "6b998eb3800f1fa9961b77d58b076cc1"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "plain-ui-kotlin-0.4.3-sources.jar",
          "url": "plain-ui-0.4.3-sources.jar",
          "size": 149974,
          "sha512": "b88d87d336799bb7504e8d22106ff5682d9630a95bd39f0781629b6e32f4e39b4aa54ad006a8ae2563b87d2546bc57a12f462e5850be0a80cc0ff0220ffb6b1b",
          "sha256": "909782f21f1e99f619f595d477599bd6dc80cb0f5bf655e1ff9ceecac3e786f6",
          "sha1": "d9c6ee5a417f4566fc3c69c44c79894e0395bbc3",
          "md5": "b9be666bb5a825ac606e0c6484503eb2"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../plain-ui-android/0.4.3/plain-ui-android-0.4.3.module",
        "group": "com.ismartcoding",
        "module": "plain-ui-android",
        "version": "0.4.3"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../plain-ui-android/0.4.3/plain-ui-android-0.4.3.module",
        "group": "com.ismartcoding",
        "module": "plain-ui-android",
        "version": "0.4.3"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../plain-ui-android/0.4.3/plain-ui-android-0.4.3.module",
        "group": "com.ismartcoding",
        "module": "plain-ui-android",
        "version": "0.4.3"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-ui-iosarm64/0.4.3/plain-ui-iosarm64-0.4.3.module",
        "group": "com.ismartcoding",
        "module": "plain-ui-iosarm64",
        "version": "0.4.3"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-ui-iosarm64/0.4.3/plain-ui-iosarm64-0.4.3.module",
        "group": "com.ismartcoding",
        "module": "plain-ui-iosarm64",
        "version": "0.4.3"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-ui-iosarm64/0.4.3/plain-ui-iosarm64-0.4.3.module",
        "group": "com.ismartcoding",
        "module": "plain-ui-iosarm64",
        "version": "0.4.3"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-ui-iosarm64/0.4.3/plain-ui-iosarm64-0.4.3.module",
        "group": "com.ismartcoding",
        "module": "plain-ui-iosarm64",
        "version": "0.4.3"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-ui-iossimulatorarm64/0.4.3/plain-ui-iossimulatorarm64-0.4.3.module",
        "group": "com.ismartcoding",
        "module": "plain-ui-iossimulatorarm64",
        "version": "0.4.3"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-ui-iossimulatorarm64/0.4.3/plain-ui-iossimulatorarm64-0.4.3.module",
        "group": "com.ismartcoding",
        "module": "plain-ui-iossimulatorarm64",
        "version": "0.4.3"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-ui-iossimulatorarm64/0.4.3/plain-ui-iossimulatorarm64-0.4.3.module",
        "group": "com.ismartcoding",
        "module": "plain-ui-iossimulatorarm64",
        "version": "0.4.3"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plain-ui-iossimulatorarm64/0.4.3/plain-ui-iossimulatorarm64-0.4.3.module",
        "group": "com.ismartcoding",
        "module": "plain-ui-iossimulatorarm64",
        "version": "0.4.3"
      }
    }
  ]
}
