{
  "formatVersion": "1.1",
  "component": {
    "url": "../../plain-ui/0.4.9/plain-ui-0.4.9.module",
    "group": "com.ismartcoding",
    "module": "plain-ui",
    "version": "0.4.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.ismartcoding",
          "module": "plain-common",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.33.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "plain-ui-iosArm64Main-0.4.9.klib",
          "url": "plain-ui-iosarm64-0.4.9.klib",
          "size": 935187,
          "sha512": "8a56d6c67cba23bc5cd92bd63b274daad4121070590e6f5decbbeffce7fecf43e60d402bb8c8fa7a5de806c38a0a97d8e19d363342ccbffc10fc9de12c418248",
          "sha256": "aebc73585eaaa18806400cf6796e08eb9d1cc803c1982c452ccf75db9b99645b",
          "sha1": "6ec0756d8ae8236dc60f8e0eadc6cf6d93822898",
          "md5": "db4e7612593f111c1881462fda95d292"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "plain-ui-iosarm64-0.4.9-sources.jar",
          "url": "plain-ui-iosarm64-0.4.9-sources.jar",
          "size": 173383,
          "sha512": "22fa9b4d1f8d523c6e3b9537a05365e31071a41f828cc84726f9bb014902cc7aff2653b09eb5eb5b73d5bae3c8e52abeec1ba39adbff660fb67f7730d8af32fc",
          "sha256": "a6715cb225e9956d4b2d7caf37f35d3cd6bd06e05f55b048507632970ccdd653",
          "sha1": "caa44e09631cd47c2ee6609771e88cf620d55305",
          "md5": "c6bb1c51c7575884dad079f96f14718d"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.ismartcoding",
          "module": "plain-common",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.33.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "plain-ui-0.4.9.kotlin_resources.zip",
          "url": "plain-ui-iosarm64-0.4.9-kotlin_resources.kotlin_resources.zip",
          "size": 117584,
          "sha512": "2571950c2f3aff591c1d774b9a66091d3686ff62a72adcf4dbc310cdf217b4df6d155748ba5160231b28404fdb0278a7935480ffee9e3d9c4d74c6c604fb801b",
          "sha256": "2bfaff3de6ae3cc0876b95d0aa5bfdb4b411c7103d97649cfa35dc3f115da40d",
          "sha1": "70fc71c266cc8a26a49be8d59b0d12cae4375130",
          "md5": "dab2200e24f923df54028989885323c2"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.ismartcoding",
          "module": "plain-common",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.33.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "plain-ui-iosarm64-0.4.9-metadata.jar",
          "url": "plain-ui-iosarm64-0.4.9-metadata.jar",
          "size": 4219,
          "sha512": "c389eeefa847ad440b71fd5b37b08095e583c8a655a2539510e1da7df90af4405030dbf1e33c6cea4cf4ae1b669f87d7ad018cb1fdde5625a96e4c387b30ccf6",
          "sha256": "66aeb56f5363ce35d1fbf5a31a28922d7808d29f9ae93474fc05e3319d08fda1",
          "sha1": "29aef41faa6f7d93afb4cb0175a670dd910fce6b",
          "md5": "998dde613930805d4dafbb69e9161fec"
        }
      ]
    }
  ]
}
