#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
LIMIT="${1:-150}"
OUT_FILE="$ROOT_DIR/docs/ui-file-length-violations.txt"

tmp_output="$(mktemp)"
tmp_error="$(mktemp)"
cleanup() {
  rm -f "$tmp_output" "$tmp_error"
}
trap cleanup EXIT

if "$ROOT_DIR/scripts/check-ui-file-length.sh" "$LIMIT" >"$tmp_output" 2>"$tmp_error"; then
  {
    echo "# Generated by scripts/update-ui-file-length-violations.sh"
    echo "# Limit: ${LIMIT}"
    cat "$tmp_output"
  } >"$OUT_FILE"
  echo "Updated $OUT_FILE (no violations)."
  exit 0
fi

{
  echo "# Generated by scripts/update-ui-file-length-violations.sh"
  echo "# Limit: ${LIMIT}"
  cat "$tmp_output"
} >"$OUT_FILE"

cat "$tmp_error" >&2
echo "Updated $OUT_FILE (violations found)." >&2
exit 1