{
  "formatVersion": "1.1",
  "component": {
    "url": "../../plain-ui/0.4.0/plain-ui-0.4.0.module",
    "group": "com.ismartcoding",
    "module": "plain-ui",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.4"
          }
        },
        {
          "group": "com.ismartcoding",
          "module": "plain-common",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.33.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "plain-ui.aar",
          "url": "plain-ui-android-0.4.0.aar",
          "size": 1076674,
          "sha512": "27ff12a16867ce61e3d330d5fe04f6aa20a7992ad3202c7a593176774a79308b9017233b058b50a5e7797490d3229673240961ef3ed70d3bbc984fcf966b2ec0",
          "sha256": "48ca0683589161af0729a25cd4c86584f72e203ffb0b273481b1130b0547fc95",
          "sha1": "a65c529c002887eda60453c70fafd12d1b0faae0",
          "md5": "a4965b26574f738f446f5cae741ac649"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.4"
          }
        },
        {
          "group": "com.ismartcoding",
          "module": "plain-common",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.33.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-compose",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "plain-ui.aar",
          "url": "plain-ui-android-0.4.0.aar",
          "size": 1076674,
          "sha512": "27ff12a16867ce61e3d330d5fe04f6aa20a7992ad3202c7a593176774a79308b9017233b058b50a5e7797490d3229673240961ef3ed70d3bbc984fcf966b2ec0",
          "sha256": "48ca0683589161af0729a25cd4c86584f72e203ffb0b273481b1130b0547fc95",
          "sha1": "a65c529c002887eda60453c70fafd12d1b0faae0",
          "md5": "a4965b26574f738f446f5cae741ac649"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "plain-ui-android-0.4.0-sources.jar",
          "url": "plain-ui-android-0.4.0-sources.jar",
          "size": 157416,
          "sha512": "32c21eeed27002ef2cf26bc01a46966267465f2c8968d6456e358c12972644f335a805f037f5cd05614b9636b0dbc9aeb10dd979e1123ec8cea4ffd6b1f9e2b0",
          "sha256": "f6307293203316277e41271abc8f609542985bcaf3c79c8688d717ce1d320e0c",
          "sha1": "523bd01b9ae92fb854c51f137a2e37174bb958a0",
          "md5": "113e38953baaeca0c65d7239ed58191b"
        }
      ]
    }
  ]
}
