{
  "formatVersion": "1.1",
  "component": {
    "url": "../../plain-common/0.1.0/plain-common-0.1.0.module",
    "group": "com.ismartcoding",
    "module": "plain-common",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-handler",
          "version": {
            "requires": "4.2.16.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-codec-http",
          "version": {
            "requires": "4.2.16.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-transport-native-epoll",
          "version": {
            "requires": "4.2.16.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-transport-native-kqueue",
          "version": {
            "requires": "4.2.16.Final"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.32.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "plain-common.aar",
          "url": "plain-common-android-0.1.0.aar",
          "size": 3038830,
          "sha512": "bf948278a634a14aa356928138e43e9af7127ea1eb8b2971f611a41af672e2289460ab738a886163431d05ba266495804cc0fa02a65c3bc2b0dc675251070d4c",
          "sha256": "d389438d282ba9cedc7d12d45289ff4f47d9a01b4f7a30aa08c4ec3950b84d47",
          "sha1": "644c9cdd367e6b5ed27cdae69f820e34dc4fe0c1",
          "md5": "d4296d681e21886c8d8689defd3e8bfc"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-handler",
          "version": {
            "requires": "4.2.16.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-codec-http",
          "version": {
            "requires": "4.2.16.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-transport-native-epoll",
          "version": {
            "requires": "4.2.16.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-transport-native-kqueue",
          "version": {
            "requires": "4.2.16.Final"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.32.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "plain-common.aar",
          "url": "plain-common-android-0.1.0.aar",
          "size": 3038830,
          "sha512": "bf948278a634a14aa356928138e43e9af7127ea1eb8b2971f611a41af672e2289460ab738a886163431d05ba266495804cc0fa02a65c3bc2b0dc675251070d4c",
          "sha256": "d389438d282ba9cedc7d12d45289ff4f47d9a01b4f7a30aa08c4ec3950b84d47",
          "sha1": "644c9cdd367e6b5ed27cdae69f820e34dc4fe0c1",
          "md5": "d4296d681e21886c8d8689defd3e8bfc"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "plain-common-android-0.1.0-sources.jar",
          "url": "plain-common-android-0.1.0-sources.jar",
          "size": 614467,
          "sha512": "12275fe90b2e5622f068ab9f8650fad81e0633dd9448fd6542d4463e4c1997fb8e77ff067879fff327026547c0956d12d19541f77bb9f20c91cf5c4ed8902a87",
          "sha256": "ee1f8fe4db7374bba2c13eabbc0e549123500afc35c3393bf51c63f5cf784ead",
          "sha1": "2c0d55820750dc5b1a46466a20f7511c3670c14e",
          "md5": "a611c38fa28cef91a83e93ebc5269a81"
        }
      ]
    }
  ]
}
