{
  "formatVersion": "1.1",
  "component": {
    "url": "../../plain-ui/0.1.0/plain-ui-0.1.0.module",
    "group": "com.ismartcoding",
    "module": "plain-ui",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "plain-ui.aar",
          "url": "plain-ui-android-0.1.0.aar",
          "size": 14121,
          "sha512": "b281f0d57c0879aff41fca66dad45b32843b4dfe6508a707b443b0fce112048907eb625f3f1d8ef94fab3fe5c536633452dfc288319bfced7a60600d8d87de49",
          "sha256": "f1716ef7feb123b551206bc3cf9b0f47593d9bd06ed7fb7212813a42b66d735e",
          "sha1": "abdb75a034bcde4324bba9ddb22ec521156deea5",
          "md5": "e0a66330764a3457b736f2ae9271acdf"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "plain-ui.aar",
          "url": "plain-ui-android-0.1.0.aar",
          "size": 14121,
          "sha512": "b281f0d57c0879aff41fca66dad45b32843b4dfe6508a707b443b0fce112048907eb625f3f1d8ef94fab3fe5c536633452dfc288319bfced7a60600d8d87de49",
          "sha256": "f1716ef7feb123b551206bc3cf9b0f47593d9bd06ed7fb7212813a42b66d735e",
          "sha1": "abdb75a034bcde4324bba9ddb22ec521156deea5",
          "md5": "e0a66330764a3457b736f2ae9271acdf"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "plain-ui-android-0.1.0-sources.jar",
          "url": "plain-ui-android-0.1.0-sources.jar",
          "size": 2797,
          "sha512": "a855ea8aa98ff2deb91983bbef5147eb312fe58a9e4a3027d5224177419980150740b1859631c96a27d8cd398a818b2ba76a29b859b5edef76d14f8b77294582",
          "sha256": "be14aabd073803fe30148c10694c4b43d063f79744e62c1debf038845f5119ed",
          "sha1": "abd951c2789e2a3d95d19ac585e61f93e0d8326d",
          "md5": "a9924d7ba1f3221d8391bdfc11ca08c1"
        }
      ]
    }
  ]
}
