{
  "formatVersion": "1.1",
  "component": {
    "url": "../../plain-ui/0.4.10/plain-ui-0.4.10.module",
    "group": "com.ismartcoding",
    "module": "plain-ui",
    "version": "0.4.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.4"
          }
        },
        {
          "group": "com.ismartcoding",
          "module": "plain-common",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.33.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "plain-ui.aar",
          "url": "plain-ui-android-0.4.10.aar",
          "size": 1169503,
          "sha512": "ccd9b8326bcaaefc650e5696e5bfd514753070081663ce033edfcf53ac56d457e7bca9f4a088bf86a39a0c99aa9823252c1fb6373ff0719e2684ba71de749346",
          "sha256": "0b4da37c57ac6c9eb6b90177c708a057b112f94749017f9f1b05f1cfa37f9805",
          "sha1": "9f5b6fa10cec2ee6b15d31c925aa52453696fbd8",
          "md5": "1f159a9e5782d6ebe252e6e2570959b0"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.4"
          }
        },
        {
          "group": "com.ismartcoding",
          "module": "plain-common",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.33.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-compose",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "plain-ui.aar",
          "url": "plain-ui-android-0.4.10.aar",
          "size": 1169503,
          "sha512": "ccd9b8326bcaaefc650e5696e5bfd514753070081663ce033edfcf53ac56d457e7bca9f4a088bf86a39a0c99aa9823252c1fb6373ff0719e2684ba71de749346",
          "sha256": "0b4da37c57ac6c9eb6b90177c708a057b112f94749017f9f1b05f1cfa37f9805",
          "sha1": "9f5b6fa10cec2ee6b15d31c925aa52453696fbd8",
          "md5": "1f159a9e5782d6ebe252e6e2570959b0"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "plain-ui-android-0.4.10-sources.jar",
          "url": "plain-ui-android-0.4.10-sources.jar",
          "size": 178291,
          "sha512": "d913c7b2b4a27b4163cb32e80fcf86ce2d36e1d8852f1551502ef310bbcd89b79a72d1763d80a193ac8b0eb09989ec9b9030340c23384be7a644760ad360e375",
          "sha256": "44dd73f7531bd1b5df71a7d0d139b88321ae2d95ef91a780780826913a0e1a24",
          "sha1": "5aed7b06208514ddcab5b0d4592176a29abb9ca3",
          "md5": "0cd8c9f3fc35929087192719a34b5e6b"
        }
      ]
    }
  ]
}
