{
  "formatVersion": "1.1",
  "component": {
    "url": "../../plain-ui/0.2.0/plain-ui-0.2.0.module",
    "group": "com.ismartcoding",
    "module": "plain-ui",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.ismartcoding",
          "module": "plain-common",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.32.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "plain-ui.aar",
          "url": "plain-ui-android-0.2.0.aar",
          "size": 843028,
          "sha512": "dcbaa66a7d4b33ed7fc6bf663cfec34f166affb5bd05a6705fbd47e1685e22c2ff2bdbf9d05de84f993ec0f80dfcda9f45a70332d3d7c43dc803a45bc0ab1aaa",
          "sha256": "67e4af0b544be13c5a835533a183d1f509a52d911e5e1ed3724c2633914c16e3",
          "sha1": "2b33bc6089b3762ccbb40e61ebec94bda8248b8a",
          "md5": "e45c5682025451de92fb91e8502c5203"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.ismartcoding",
          "module": "plain-common",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.32.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "plain-ui.aar",
          "url": "plain-ui-android-0.2.0.aar",
          "size": 843028,
          "sha512": "dcbaa66a7d4b33ed7fc6bf663cfec34f166affb5bd05a6705fbd47e1685e22c2ff2bdbf9d05de84f993ec0f80dfcda9f45a70332d3d7c43dc803a45bc0ab1aaa",
          "sha256": "67e4af0b544be13c5a835533a183d1f509a52d911e5e1ed3724c2633914c16e3",
          "sha1": "2b33bc6089b3762ccbb40e61ebec94bda8248b8a",
          "md5": "e45c5682025451de92fb91e8502c5203"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "plain-ui-android-0.2.0-sources.jar",
          "url": "plain-ui-android-0.2.0-sources.jar",
          "size": 138453,
          "sha512": "cb2abafb14e7d0285d7377689b89ffbc7e92e0a92089e7bfb1cf4c9da6a4ffcf86dd4bec4c77d58d8976d303f435ce5de4a55b68032768be8e884a2469e5ae78",
          "sha256": "65dba090de6c36ea0f82f7bd70f4b6d1ebc16420473bc94b20c4a78e346e9ea1",
          "sha1": "7582a5c850c283f6be5c5bb00520fb44019b9735",
          "md5": "1a9d59e8f376aa2d05470e0dd5bb7a46"
        }
      ]
    }
  ]
}
