{
  "formatVersion": "1.1",
  "component": {
    "url": "../../plain-ui/0.4.5/plain-ui-0.4.5.module",
    "group": "com.ismartcoding",
    "module": "plain-ui",
    "version": "0.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.4"
          }
        },
        {
          "group": "com.ismartcoding",
          "module": "plain-common",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.33.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "plain-ui.aar",
          "url": "plain-ui-android-0.4.5.aar",
          "size": 1134512,
          "sha512": "36f68afff69dd69a9a5c392d97c939c3133f343b05de7a1a6ac3d042f60581125e48b438ade024441826a7211380eec09d0aaaebcf42f7c6372a02aa0c871a37",
          "sha256": "d4c1472f59bb039e3e833e146b5ce21540688669e43836920387765416ac953f",
          "sha1": "adbb1867e55699476769cbe7f8266e7b3dfd5589",
          "md5": "fb61554fde8d52e88bcbde1b28c01843"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.4"
          }
        },
        {
          "group": "com.ismartcoding",
          "module": "plain-common",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.33.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-compose",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "plain-ui.aar",
          "url": "plain-ui-android-0.4.5.aar",
          "size": 1134512,
          "sha512": "36f68afff69dd69a9a5c392d97c939c3133f343b05de7a1a6ac3d042f60581125e48b438ade024441826a7211380eec09d0aaaebcf42f7c6372a02aa0c871a37",
          "sha256": "d4c1472f59bb039e3e833e146b5ce21540688669e43836920387765416ac953f",
          "sha1": "adbb1867e55699476769cbe7f8266e7b3dfd5589",
          "md5": "fb61554fde8d52e88bcbde1b28c01843"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "plain-ui-android-0.4.5-sources.jar",
          "url": "plain-ui-android-0.4.5-sources.jar",
          "size": 170164,
          "sha512": "2346ea8e25cb7d87e27d07eade5bb07b03b6eecbb25fd71d37393572936068290571806f9ca2a9c774ef4722251968af6981583c3e34ef96f3ae37ce6ff5c060",
          "sha256": "92dfee651d805b3cec2201a771fd641b8243558b5f7d215d67cf3bab62a2a180",
          "sha1": "fa0ccf50740e55cd33048f76c1911ecb43198ffa",
          "md5": "8aef4a552973595a876390590c50277a"
        }
      ]
    }
  ]
}
